### ISSUE TITLE
Bug in notebook bumps_ChudleyElliotDiff_fit.ipynb

### ISSUE THREAD

**Issue by celinedurniak** [QENSlibrary/QENSmodels#8]
**Describe the bug**
This is a problem with the plotting feature of new versions of bumps (from version 0.7.13 and above).

**To Reproduce**
1. Execute the cells of bumps_ChudleyElliotDiff_fit.ipynb
2. When executing "problem.plot()", you should get an error "IndexError: too many indices for array"

**Expected behavior**
Instead you should have a plot of the experimental data and the fitting model

**Comment by celinedurniak** [comment]
Temporary solution: specify version of bumps (0.7.12) to be installed in Jupyter notebook

**Comment by TOFarmer** [comment]
One minor issue with this is that bumps versions <0.7.14 are not compatible with Python 3.8 (due to the removal of `time.clock`, see [here](https://github.com/bumps/bumps/releases) for further details).  Depending on how long Celine's temporary solution lasts, it might be worth either noting this in the documentation or adding `python_requires` to setup.py.
